services:
  db:
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080