services:
  db:
    image: postgres:16
    ports:
      - "8000:5000"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080